trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: '1.6.0'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: $(TF_VERSION)

variables:
  ARM_CLIENT_ID: '$(CLIENT_ID)'
  ARM_CLIENT_SECRET: '$(CLIENT_SECRET)'
  ARM_SUBSCRIPTION_ID: '$(SUBSCRIPTION_ID)'
  ARM_TENANT_ID: '$(TENANT_ID)'




# ✅ Authenticate to Azure using the service connection
- task: AzureCLI@2
  inputs:
    azureSubscription: 'WaTech-AID-IAC-Project'  # Service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Init and apply
      terraform init -reconfigure
      terraform plan -out=tfplan
      terraform apply -auto-approve tfplan
