trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: '1.6.0'
  CLIENT_ID: $(CLIENT_ID)
  CLIENT_SECRET: $(CLIENT_SECRET)
  SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
  TENANT_ID: $(TENANT_ID)

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: $(TF_VERSION)


- task: AzureCLI@2
  inputs:
    azureSubscription: 'WaTech-AID-IAC-Project'  # Service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Init and apply
      terraform init -reconfigure
      terraform plan -out=tfplan
      terraform apply -auto-approve tfplan
